-- Table for Approval Requests
CREATE TABLE APPROVAL_REQUESTS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REQUEST_DATA VARCHAR2(4000), -- JSON or Text details of the request
    APP_FLAG CHAR(1) CHECK (APP_FLAG IN ('y', 'n')), -- 'y' means show in app
    EMAIL_FLAG CHAR(1) CHECK (EMAIL_FLAG IN ('y', 'n')), -- 'y' means send email
    STATUS CHAR(1) DEFAULT 'P' CHECK (STATUS IN ('P', 'A', 'R')), -- P=Pending, A=Approved, R=Rejected
    USER_EMAIL VARCHAR2(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster retrieval of pending requests
CREATE INDEX IDX_APPROVAL_STATUS ON APPROVAL_REQUESTS(STATUS);
